default:
  CCRI parameters:
    Hosts:
      monfreda: ["avocado"]
      mapspam: 
      file:
    HostDensityThreshold: [0.00015]
    AggregationStrategy: [sum, mean]
    Resolution: 12
    GeoExtent: 
      global: TRUE
      customExt: [ -140, -34, -58, 60 ] # set this to NA/Empty if not required #[32, 48, 2.9, 17], [-115, -75, 5, 32]
    LinkThreshold: [0, 0.000001, 0.00006]
    DispersalKernelModels:
      beta: [0.5, 1, 1.5]
      gamma: [0.05, 1, 0.2, 0.3]
    NetworkMetrics:
      InversePowerLaw:
        metrics: ["betweeness", "NODE_STRENGTH", "Sum_of_nearest_neighbors", "eigenVector_centrAlitY"]
        weights: [50, 15, 15, 20]
      NegativeExponential:
        metrics: ["betweeness", "NODE_STRENGTH", "Sum_of_nearest_neighbors", "eigenVector_centrAlitY"]
        weights: [50, 15, 15, 20]
    PriorityMaps:
      MeanCC: TRUE
      Difference: TRUE
      Variance: TRUE
