default:
  CCRI parameters:
    Hosts:
      monfreda: ["avocado"]
      mapspam2010: ["sorghum"]
      mapspam2017Africa:
      file:
    HostDensityThreshold: [0.00015, 0.000025]
    AggregationStrategy: [sum, mean]
    DistanceStrategy: "geodesic"
    Resolution: 12
    GeoExtent: 
      global: FALSE
      customExt:
    LinkThreshold: [0.000001]
    DispersalKernelModels:
      InversePowerLaw:
        beta: [0.5, 1, 1.5]
      NegativeExponential:
        gamma: [0.05, 1, 0.2, 0.3]
    NetworkMetrics:
      InversePowerLaw:
        metrics: ["betweeness"]
        weights: [100]
        cutoff: -1
      NegativeExponential:
        metrics: ["betweeness"]
        weights: [100]
        cutoff: -1
    PriorityMaps:
      OutDir: "C:/Users/kkeshav/Desktop/test"
      MeanCC: TRUE
      Difference: TRUE
      Variance: TRUE
