default:
  CCRI parameters:
    Beta:
      - 0.5
      - 1
      - 1.5
      - 1.5
    Gamma:
      - 0.05
      - 0.1
      - 0.2
      - 0.3
      - 1
    AggregationStrategy: [sum, mean]
    Crops: ["avocado"]
    CropLandThreshold: [0.0002, 0.5, 0.8] #cuttoff - run SA for each of these
    LinkWeight: [0, 0.000001, 0.5, 0.6]
    Longitude_Latitude: 
      Global: TRUE
      WestExt: [-24, 180, -58, 60] #long_from, long_to, lat_from, lat_to
      EastExt: [-140, -34, -58, 60]
      CustomExt: [] # set this to NA/Empty if not required
    Resolution: 24
    Network_metrics:
      InversePowerLaw: ["betweeness", "node_strength", "sum_of_nearest_neghbors", "eigenvector_centrality"]
      NegativeExponential: ["betweeness", "node_strength", "sum_of_nearest_neghbors", "eigenvector centrality"]
    OutcomeAnalysis:
      MeanCC: TRUE
      Difference: TRUE
      Variance: TRUE
    SaveOutcomes:
      MeanCC: TRUE
      Difference: TRUE
      Variance: TRUE
