default:
  CCRI parameters:
    beta:
      - 0.5
      - 1
      - 1.5
    gamma:
      - 0.05
      - 0.1
      - 0.2
      - 0.3
      - 1
    crop: "avocado"
    cuttoff: 0.0001
    cuttoff AM: 0
    longitude_latitude: [[-24, 180, -58, 60]] #long_from, long_to, lat_from, lat_to
    Area Size:
    Resolution: 12
    Network_metrics: ["betweeness", "node_strength", "sum_of_nearest_neghbors", "node_degree", "eigenvector centrality"]
